---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cowsay
  name: cowsay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cowsay
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cowsay
    spec:
      containers:
        - image: danielguo/cowsay-web-app:latest
          imagePullPolicy: IfNotPresent
          name: cowsay
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cowsay
  name: cowsay
spec:
  ports:
    - port: 8080
  selector:
    app: cowsay